//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 4 view controllers.
  struct segue {
    /// This struct is generated for `HomeP`, and contains static references to 1 segues.
    struct homeP {
      /// Segue identifier `HomeV`.
      static let homeV: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, HomeP, HomeV> = Rswift.StoryboardSegueIdentifier(identifier: "HomeV")
      
      /// Optionally returns a typed version of segue `HomeV`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func homeV(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, HomeP, HomeV>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.homeP.homeV, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `HomeV`, and contains static references to 2 segues.
    struct homeV {
      /// Segue identifier `LatestPlaceP`.
      static let latestPlaceP: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, HomeV, LatestPlaceP> = Rswift.StoryboardSegueIdentifier(identifier: "LatestPlaceP")
      /// Segue identifier `MostPopularP`.
      static let mostPopularP: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, HomeV, MostPopularP> = Rswift.StoryboardSegueIdentifier(identifier: "MostPopularP")
      
      /// Optionally returns a typed version of segue `LatestPlaceP`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func latestPlaceP(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, HomeV, LatestPlaceP>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.homeV.latestPlaceP, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `MostPopularP`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func mostPopularP(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, HomeV, MostPopularP>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.homeV.mostPopularP, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `LatestPlaceP`, and contains static references to 1 segues.
    struct latestPlaceP {
      /// Segue identifier `LatestPlaceV`.
      static let latestPlaceV: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, LatestPlaceP, LatestPlaceV> = Rswift.StoryboardSegueIdentifier(identifier: "LatestPlaceV")
      
      /// Optionally returns a typed version of segue `LatestPlaceV`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func latestPlaceV(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, LatestPlaceP, LatestPlaceV>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.latestPlaceP.latestPlaceV, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `MostPopularP`, and contains static references to 1 segues.
    struct mostPopularP {
      /// Segue identifier `MostPopularV`.
      static let mostPopularV: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, MostPopularP, MostPopularV> = Rswift.StoryboardSegueIdentifier(identifier: "MostPopularV")
      
      /// Optionally returns a typed version of segue `MostPopularV`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func mostPopularV(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, MostPopularP, MostPopularV>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.mostPopularP.mostPopularV, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `main`.
    static let main = _R.storyboard.main()
    /// Storyboard `places`.
    static let places = _R.storyboard.places()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    /// `UIStoryboard(name: "places", bundle: ...)`
    static func places(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.places)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try places.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = MainMVP
      
      let bundle = R.hostingBundle
      let homeP = StoryboardViewControllerResource<HomeP>(identifier: "HomeP")
      let mainMVP = StoryboardViewControllerResource<MainMVP>(identifier: "MainMVP")
      let name = "main"
      
      func homeP(_: Void = ()) -> HomeP? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: homeP)
      }
      
      func mainMVP(_: Void = ()) -> MainMVP? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainMVP)
      }
      
      static func validate() throws {
        if _R.storyboard.main().homeP() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'homeP' could not be loaded from storyboard 'main' as 'HomeP'.") }
        if _R.storyboard.main().mainMVP() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mainMVP' could not be loaded from storyboard 'main' as 'MainMVP'.") }
      }
      
      fileprivate init() {}
    }
    
    struct places: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let latestPlaceP = StoryboardViewControllerResource<LatestPlaceP>(identifier: "LatestPlaceP")
      let mostPopularP = StoryboardViewControllerResource<MostPopularP>(identifier: "MostPopularP")
      let name = "places"
      
      func latestPlaceP(_: Void = ()) -> LatestPlaceP? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: latestPlaceP)
      }
      
      func mostPopularP(_: Void = ()) -> MostPopularP? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mostPopularP)
      }
      
      static func validate() throws {
        if _R.storyboard.places().latestPlaceP() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'latestPlaceP' could not be loaded from storyboard 'places' as 'LatestPlaceP'.") }
        if _R.storyboard.places().mostPopularP() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'mostPopularP' could not be loaded from storyboard 'places' as 'MostPopularP'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
