platform :ios, '9.0'

def shared_pods
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # ignore all warnings from all pods
    inhibit_all_warnings!
    
    # QA and CI
    pod 'SwiftLint', '~> 0.16.1'
    
end

target ‘ArchTemp’ do
    shared_pods
    
    target 'ArchTempTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
